---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
platforms:
  - name: ubuntu-16.04
    image: ubuntu:16.04
  - name: ubuntu-18.04
    image: ubuntu:18.04
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
