---
- name: Converge
  hosts: all
  become: !!bool True
  roles:
    - role: FGtatsuro.java
    - role: ansible-role-android
      android_home: /var/lib/android-tools
      android_extra_components:
        - extras;android;m2repository
        - build-tools;27.0.3
        - platforms;android-27
